name: PR Merge to Master or Main

on:
  pull_request:
    types: [ closed ]

jobs:
  merge-job:
    if: github.event.pull_request.merged == true &&
      (github.event.pull_request.base.ref == 'master' || github.event.pull_request.base.ref == 'main') &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: self-hosted
    env:
      ANDROID_HOME: /Users/miam/Library/Android/sdk
    steps:
      - uses: actions/checkout@v3
      - name: Extract version from branch name
        id: extract_version
        run: |
          # Extract the branch name from GITHUB_REF
          BRANCH_NAME="${GITHUB_HEAD_REF}"
          
          # Use regex to extract the version number (assuming format like release/x.y.z)
          if [[ "$BRANCH_NAME" =~ release/([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "Version extracted: $VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "No version number found in branch name"
            exit 1
          fi

      - name: Build dist folder
        run: |
          echo Using version: ${{ steps.extract_version.outputs.version }}
          make js VERSION=${{ steps.extract_version.outputs.version }} ENV=prod

      - name: Test with Gradle
        run: ./gradlew test -Pstaging=true

      - name: npm release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd mealzSharedAnalytics/dist
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
          npm publish

      - name: fastlane release
        run: fastlane release version:${{ steps.extract_version.outputs.version }} env:release
